[2024-07-16T10:13:24.453+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-16T10:13:24.510+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xcom_dag.branch manual__2024-07-16T10:13:21.455494+00:00 [queued]>
[2024-07-16T10:13:24.514+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xcom_dag.branch manual__2024-07-16T10:13:21.455494+00:00 [queued]>
[2024-07-16T10:13:24.520+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-16T10:13:24.547+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): branch> on 2024-07-16 10:13:21.455494+00:00
[2024-07-16T10:13:24.555+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1957) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-16T10:13:24.569+0000] {standard_task_runner.py:63} INFO - Started process 1958 to run task
[2024-07-16T10:13:24.571+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xcom_dag', 'branch', 'manual__2024-07-16T10:13:21.455494+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/xcom_dags.py', '--cfg-path', '/tmp/tmpfkb4ih0c']
[2024-07-16T10:13:24.573+0000] {standard_task_runner.py:91} INFO - Job 108: Subtask branch
[2024-07-16T10:13:24.671+0000] {task_command.py:426} INFO - Running <TaskInstance: xcom_dag.branch manual__2024-07-16T10:13:21.455494+00:00 [running]> on host 2f80c3cf662d
[2024-07-16T10:13:24.804+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xcom_dag' AIRFLOW_CTX_TASK_ID='branch' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T10:13:21.455494+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T10:13:21.455494+00:00'
[2024-07-16T10:13:24.804+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-16T10:13:24.811+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-07-16T10:13:24.829+0000] {python.py:237} INFO - Done. Returned value was: t2
[2024-07-16T10:13:24.829+0000] {branch.py:36} INFO - Branch into t2
[2024-07-16T10:13:24.829+0000] {skipmixin.py:178} INFO - Following branch t2
[2024-07-16T10:13:24.845+0000] {skipmixin.py:246} INFO - Skipping tasks [('t3', -1)]
[2024-07-16T10:13:24.865+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-16T10:13:24.883+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=xcom_dag, task_id=branch, run_id=manual__2024-07-16T10:13:21.455494+00:00, execution_date=20240716T101321, start_date=20240716T101324, end_date=20240716T101324
[2024-07-16T10:13:24.921+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-16T10:13:24.967+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-16T10:13:24.970+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
